In [1]:
print('Hi')

Hi


In [41]:
import pandas as pd

In [3]:
import numpy as np

In [7]:
a = np.array([[1, 2, 3, 3, 1],[6, 8, 11, 10, 7]]).transpose()
print(a)

[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]


In [9]:
mean_a = np.mean(a, axis = 0)
mean_a

array([2. , 8.4])

In [10]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [22]:
a_centered_sp = a_centered.T[0] @ a_centered.T[1]
a_centered_sp

8.0

In [27]:
a_centered_sp = a_centered_sp / (a_centered.shape[0] - 1)
a_centered_sp

0.0

In [25]:
np.cov(a.T)[0, 1]

2.0

In [7]:
authors = pd.DataFrame({'author_name': ['Тургенев', 'Чехов', 'Островский'], 'author_id': [1, 2, 3]})

In [8]:
authors

author_name  author_id
0    Тургенев          1
1       Чехов          2
2  Островский          3

In [9]:
book = pd.DataFrame({'author_id': [1, 1, 1, 2, 2, 3, 3], 'book_title': ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'], 'price': [394, 5756,888,483,7474,875,3948]})

In [10]:
book

author_id            book_title  price
0          1           Отцы и дети    394
1          1                 Рудин   5756
2          1     Дворянское гнездо    888
3          2      Толстый и тонкий    483
4          2       Дама с собачкой   7474
5          3                 Гроза    875
6          3  Таланты и поклонники   3948

In [11]:
authors_price = pd.concat([authors, book])

authors_price = authors.merge(book, on=["author_id"])
authors_price

author_name  author_id            book_title  price
0    Тургенев          1           Отцы и дети    394
1    Тургенев          1                 Рудин   5756
2    Тургенев          1     Дворянское гнездо    888
3       Чехов          2      Толстый и тонкий    483
4       Чехов          2       Дама с собачкой   7474
5  Островский          3                 Гроза    875
6  Островский          3  Таланты и поклонники   3948

In [12]:
top5 = authors_price.nlargest(5, 'price')
print(top5)

  author_name  author_id            book_title  price
4       Чехов          2       Дама с собачкой   7474
1    Тургенев          1                 Рудин   5756
6  Островский          3  Таланты и поклонники   3948
2    Тургенев          1     Дворянское гнездо    888
5  Островский          3                 Гроза    875


In [13]:
authors_stat = authors_price['author_name'].value_counts()
authors_stat = authors_price.groupby('author_name').agg({'price':['min', 'max', 'mean']})
authors_stat = authors_stat.rename(columns={'min':'min_price', 'max':'max_price', 'mean':'mean_price'})
print(authors_stat)

                price                     
            min_price max_price mean_price
author_name                               
Островский        875      3948     2411.5
Тургенев          394      5756     2346.0
Чехов             483      7474     3978.5


In [14]:
authors_price['cover'] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
authors_price

author_name  author_id            book_title  price    cover
0    Тургенев          1           Отцы и дети    394  твердая
1    Тургенев          1                 Рудин   5756   мягкая
2    Тургенев          1     Дворянское гнездо    888   мягкая
3       Чехов          2      Толстый и тонкий    483  твердая
4       Чехов          2       Дама с собачкой   7474  твердая
5  Островский          3                 Гроза    875   мягкая
6  Островский          3  Таланты и поклонники   3948   мягкая

In [35]:
book_info = pd.pivot_table(authors_price, values='price', index=['author_name'], columns=['cover'])
book_info['мягкая'] = book_info['мягкая'].fillna(0)
book_info['твердая'] = book_info['твердая'].fillna(0)
book_info

cover        мягкая  твердая
author_name                 
Островский   2411.5      0.0
Тургенев     3322.0    394.0
Чехов           0.0   3978.5

In [38]:
book_info.to_pickle('book_info.pkl')

In [39]:
book_info2 = pd.read_pickle('book_info.pkl')

In [40]:
book_info.equals(book_info2)

True